CREATE TABLE Users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(30) NOT NULL,
  lastname VARCHAR(30) NOT NULL,
  email VARCHAR(50) UNIQUE,
  mdp VARCHAR(50),
  birthdate DATE,
  administrator BOOLEAN 
);

CREATE TABLE BPM (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Valeur SMALLINT NOT NULL,
  Temps TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Personid INT(6)
);

CREATE TABLE Humidity LIKE BPM;
CREATE TABLE Temperature LIKE BPM;
CREATE TABLE Noise LIKE BPM;
CREATE TABLE Co2 LIKE BPM;

CREATE TABLE Statistics (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  BPMMax SMALLINT NOT NULL,
  BPMMin SMALLINT NOT NULL,
  BPMMoy SMALLINT NOT NULL,
  HumidityMax SMALLINT NOT NULL,
  HumidityMin SMALLINT NOT NULL,
  HumidityMoy SMALLINT NOT NULL,
  TemperatureMax SMALLINT NOT NULL,
  TemperatureMin SMALLINT NOT NULL,
  TemperatureMoy SMALLINT NOT NULL,
  NoiseMax SMALLINT NOT NULL,
  NoiseMin SMALLINT NOT NULL,
  NoiseMoy SMALLINT NOT NULL,
  Co2Max SMALLINT NOT NULL,
  Co2Min SMALLINT NOT NULL,
  Co2Moy SMALLINT NOT NULL,
  MesureDate DATE NOT NULL DEFAULT CURRENT_DATE,
  Personid INT(6)
);

CREATE TABLE faq (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    reponse VARCHAR(255)
);